name: revoNPCShop
version: '${project.version}'
main: net.revolution.revonpcshop.RevoNPCShop
api-version: '1.20'


depend:
  - PlayerNPC # https://www.spigotmc.org/resources/%E2%9C%85-api-player-npc-%E2%9C%85-1-17-1-20-1.93625/


commands:
  spawnnpc:
  removenps:
